# Generated by Django 4.2.3 on 2024-06-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_rename_text_question_content_alter_choice_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='grade_point',
            new_name='grade',
        ),
    ]
